# Generated by Django 4.0.3 on 2022-03-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='coaches.coach', verbose_name='Coach')),
            ],
        ),
    ]
