# Generated by Django 4.0.3 on 2022-03-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Team Code'),
        ),
    ]
