# Generated by Django 4.0.3 on 2022-03-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachesv2', '0003_alter_coach_user'),
        ('teams', '0002_alter_team_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='coachesv2.coach', verbose_name='Coach'),
        ),
    ]
