# Generated by Django 4.0.3 on 2022-03-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_team'),
        ('teams', '0002_team_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='players.player', verbose_name='Player'),
        ),
    ]
