# Generated by Django 4.0.3 on 2022-03-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
    ]
