# Generated by Django 4.0.3 on 2022-03-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_user'),
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='fixtures.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='players.player', verbose_name='Player Score'),
        ),
    ]
