# Generated by Django 4.0.3 on 2022-03-20 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sitestats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 7, 49, 50, 156440, tzinfo=utc), verbose_name='login time'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='logout_time',
            field=models.DateTimeField(null=True, verbose_name='logout time'),
        ),
    ]
