# Generated by Django 4.0.3 on 2022-03-20 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sitestats', '0002_alter_stat_login_time_alter_stat_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 12, 48, 28, 852069, tzinfo=utc), verbose_name='login time'),
        ),
    ]
