# Generated by Django 4.0.3 on 2022-03-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[('A', 'Admin'), ('C', 'Coach'), ('P', 'Player')], default=1),
        ),
    ]
