# Generated by Django 4.0.3 on 2022-03-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_team'),
        ('players', '0002_remove_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teams.team', verbose_name='Team'),
        ),
    ]
